language: ruby
rvm: 2.2
before_install:
  - nvm install 6
install: script/bootstrap
script: script/cibuild
cache:
  directories:
    - vendor/bundle
    - node_modules
env:
  matrix:
    - TEST_SUITE=node
    - TEST_SUITE=ruby
branches:
  only:
    - master
    - travis-trials
